project:
  type: website
  output-dir: docs


website:
  title: "Website 515"
  navbar:
    left:
      - index.qmd
      - about.qmd
      - hello.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

